-- Adopt @geiger/rbac
--
-- Storage for the suite authorization engine. Mirrors geiger-events'
-- adopt_rbac (20260804211527) with the comms namespace; comms has no earlier
-- roles overlay, so there is nothing to backfill — only the storage half, an
-- Owner role per project, and the membership bootstrap RPC.
--
-- Owns:
--   public.roles                    shared role definitions (suite-wide)
--   comms.role_grants               this product's assignments
--   public.rbac_key_matches(...)    wildcard matching, mirrors @geiger/rbac keys.js
--   comms.rbac_allows(...)          the predicate RLS policies call
--   comms.can_access_project(...)   org-membership check, ported from events
--   comms.rbac_ensure_membership()  grants the first role to someone who can
--                                   already reach the project, and never revives
--                                   a grant somebody revoked
--
-- The storage half below the first rule line is generated by @geiger/rbac's
-- migrationSql("comms") — do not hand-edit it; regenerate from the package if
-- the format changes.
--
-- NOTE ON ENFORCEMENT. This migration only creates and populates the
-- authorization tables. It does NOT replace any product table's `using (true)`
-- demo policy — flipping those is a separate, deliberate migration per table,
-- because a missing grant becomes a blank screen rather than a hidden button
-- the moment it lands.

-- @up

create extension if not exists pgcrypto;
create schema if not exists comms;
grant usage on schema comms to anon, authenticated, service_role;

-- Shared updated_at trigger for the authorization tables. Declared here (rather
-- than depending on a product's own touch_updated_at) so this block stands alone
-- whichever product runs it first.
create or replace function public.rbac_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Wildcard permission matching. Mirrors keys.js: "*" matches everything,
-- "<product>.*" and "<product>.<resource>.*" match by prefix, anything else is
-- an exact match. Immutable so it can be used in an index if that day comes.
create or replace function public.rbac_key_matches(p_patterns text[], p_key text)
returns boolean
language sql
immutable
as $$
  select exists (
    select 1
    from unnest(coalesce(p_patterns, '{}'::text[])) as pat
    where pat = '*'
       or pat = p_key
       or (
         right(pat, 2) = '.*'
         and left(p_key, length(pat) - 1) = left(pat, length(pat) - 1)
       )
  );
$$;

-- Shared role definitions. project_id scopes a role to one workspace; a null
-- project_id is a suite-wide template. permissions[] holds keys and wildcard
-- patterns spanning every product (comms.conversation.close, flow.issue.close,
-- "*").
create table if not exists public.roles (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade,
  key text,
  name text not null default 'Untitled role',
  description text not null default '',
  color text not null default 'slate',
  permissions text[] not null default '{}',
  is_system boolean not null default false,
  sort integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

alter table public.roles add column if not exists key text;
alter table public.roles add column if not exists permissions text[] not null default '{}';
alter table public.roles add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table public.roles add column if not exists deleted_at timestamptz;

create index if not exists roles_project_idx
  on public.roles (project_id) where deleted_at is null;
create unique index if not exists roles_project_key_uniq
  on public.roles (project_id, key) where key is not null and deleted_at is null;

drop trigger if exists roles_touch_updated_at on public.roles;
create trigger roles_touch_updated_at
before update on public.roles
for each row execute function public.rbac_touch_updated_at();

-- Per-product assignment. One row per (user, role) in a project. scope narrows
-- the grant to specific resources: {"conversation": ["<uuid>", ...]}. An empty
-- scope means the grant applies everywhere in the project.
create table if not exists comms.role_grants (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade,
  user_id uuid not null,
  role_id uuid not null references public.roles(id) on delete cascade,
  scope jsonb not null default '{}'::jsonb,
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  granted_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

alter table comms.role_grants add column if not exists scope jsonb not null default '{}'::jsonb;
alter table comms.role_grants add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table comms.role_grants add column if not exists deleted_at timestamptz;

-- The lookup rbac_allows() makes on every row of every gated query.
create index if not exists comms_role_grants_lookup_idx
  on comms.role_grants (user_id, project_id) where deleted_at is null;
create index if not exists comms_role_grants_role_idx
  on comms.role_grants (role_id) where deleted_at is null;
create unique index if not exists comms_role_grants_uniq
  on comms.role_grants (project_id, user_id, role_id) where deleted_at is null;

drop trigger if exists role_grants_touch_updated_at on comms.role_grants;
create trigger role_grants_touch_updated_at
before update on comms.role_grants
for each row execute function public.rbac_touch_updated_at();

-- The predicate every gated policy calls.
--
-- SECURITY DEFINER so a user can be authorized by grant rows they cannot
-- themselves select — otherwise the grants table's own RLS would have to be
-- open for authorization to work at all. STABLE so Postgres may cache it within
-- a statement rather than re-running it per row.
--
-- p_scope_type null  -> the permission is unscopeable; grants apply everywhere.
-- grant has no entry for p_scope_type -> that grant is unscoped. (Absence is
-- "no restriction", matching scope.js.)
create or replace function comms.rbac_allows(
  p_permission text,
  p_project uuid default null,
  p_scope_type text default null,
  p_scope_id uuid default null
)
returns boolean
language sql
stable
security definer
set search_path = public, comms
as $$
  select exists (
    select 1
    from comms.role_grants g
    join public.roles r on r.id = g.role_id
    where g.user_id = auth.uid()
      and g.status = 'active'
      and g.deleted_at is null
      and r.deleted_at is null
      and (p_project is null or g.project_id = p_project)
      and public.rbac_key_matches(r.permissions, p_permission)
      and (
        p_scope_type is null
        or not jsonb_exists(g.scope, p_scope_type)
        or (
          p_scope_id is not null
          and jsonb_exists(g.scope -> p_scope_type, p_scope_id::text)
        )
      )
  );
$$;

grant execute on function comms.rbac_allows(text, uuid, text, uuid) to anon, authenticated;
grant execute on function public.rbac_key_matches(text[], text) to anon, authenticated;

alter table public.roles enable row level security;
alter table comms.role_grants enable row level security;

drop policy if exists roles_read on public.roles;
create policy roles_read on public.roles
  for select to anon, authenticated using (deleted_at is null);

drop policy if exists roles_write on public.roles;
create policy roles_write on public.roles
  for all to authenticated using (true) with check (true);

drop policy if exists role_grants_read on comms.role_grants;
create policy role_grants_read on comms.role_grants
  for select to anon, authenticated using (deleted_at is null);

drop policy if exists role_grants_write on comms.role_grants;
create policy role_grants_write on comms.role_grants
  for all to authenticated using (true) with check (true);

-- ---------------------------------------------------------------------------
-- Access helper + bootstrap. Comms-specific from here down.
-- ---------------------------------------------------------------------------

-- Membership is org-level: a project inherits its members from its owning org
-- (the same chain every demo policy will narrow along when enforcement lands).
-- SECURITY DEFINER so it can read the shared public tables regardless of their
-- own RLS. Mirrors events.can_access_project and reuses the canonical
-- public.is_org_member(); treats a project with no organization as open.
create or replace function comms.can_access_project(target uuid)
returns boolean
language sql
stable
security definer
set search_path = public, comms, auth
as $$
  select exists (
    select 1
    from public.projects p
    where p.id = target
      and (
        p.organization_id is null
        or public.is_org_member(p.organization_id)
        or p.created_by = auth.uid()
      )
  );
$$;

grant execute on function comms.can_access_project(uuid) to anon, authenticated;

-- Every project gets an Owner role up front: its permission list is the stable
-- wildcard, so it keeps granting new permissions as the catalog grows. Only
-- Owner is seeded here; the other system roles are defined in
-- geiger-rbac.config.js and are seeded by the app (ensureSystemRoles) so the
-- catalog stays their single source of truth.
insert into public.roles (project_id, key, name, description, color, permissions, is_system, sort)
select p.id, 'owner', 'Owner',
       'Full access to everything, including billing.', 'violet',
       array['*'], true, 0
from public.projects p
where p.deleted_at is null
  and not exists (
    select 1 from public.roles r
    where r.project_id = p.id and r.key = 'owner' and r.deleted_at is null
  );

-- The project's creator holds Owner. Guarantees every project has at least one
-- account that can administer roles before any UI gate switches on.
insert into comms.role_grants (project_id, user_id, role_id, status)
select p.id, p.created_by, r.id, 'active'
from public.projects p
join public.roles r
  on r.project_id = p.id and r.key = 'owner' and r.deleted_at is null
where p.deleted_at is null
  and p.created_by is not null
on conflict (project_id, user_id, role_id) where deleted_at is null do nothing;

-- Make sure the caller holds a role in this project, minting one only for
-- somebody who can already reach it and has never held any. Wrapping the
-- org-membership check in the database means a caller cannot grant themselves
-- access to a project they cannot see, and a revoked grant is never handed
-- back. Comms keeps no per-project member roster, so unlike events there is no
-- roster sync here — the Team surface reads grants directly.
--
-- Returns the role id they hold afterwards, or null when they should have none.
create or replace function comms.rbac_ensure_membership(
  p_project_id uuid,
  p_default_role uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = public, comms, auth
as $$
declare
  v_uid uuid := auth.uid();
  v_creator uuid;
  v_role uuid;
  v_existing uuid;
  v_ever integer;
begin
  if p_project_id is null or v_uid is null then
    return null;
  end if;

  -- The same access check every gated table's RLS will make.
  if not comms.can_access_project(p_project_id) then
    return null;
  end if;

  select role_id into v_existing
    from comms.role_grants
   where project_id = p_project_id
     and user_id = v_uid
     and deleted_at is null
     and status = 'active'
   limit 1;

  if v_existing is not null then
    return v_existing;
  end if;

  -- A revoked grant is a decision, not a gap. Never hand one back.
  select count(*) into v_ever
    from comms.role_grants
   where project_id = p_project_id
     and user_id = v_uid;

  if v_ever > 0 then
    return null;
  end if;

  select created_by into v_creator from public.projects where id = p_project_id;

  -- Owner for the project's creator — and for the first person into a project
  -- that has no active grant at all, so a workspace is never administrable by
  -- nobody.
  select count(*) into v_ever
    from comms.role_grants
   where project_id = p_project_id
     and deleted_at is null
     and status = 'active';

  if v_creator = v_uid or v_ever = 0 then
    select r.id into v_role from public.roles r
     where r.project_id = p_project_id and r.key = 'owner' and r.deleted_at is null
     limit 1;
  end if;

  if v_role is null then
    select coalesce(
             p_default_role,
             (select r.id from public.roles r
               where r.project_id = p_project_id
                 and r.key = 'member'
                 and r.deleted_at is null
               limit 1)
           )
      into v_role;
  end if;

  if v_role is null then
    return null;   -- roles not seeded yet; the next pass picks it up
  end if;

  insert into comms.role_grants (project_id, user_id, role_id, status)
  values (p_project_id, v_uid, v_role, 'active')
  on conflict do nothing;

  return v_role;
end;
$$;

grant execute on function comms.rbac_ensure_membership(uuid, uuid) to anon, authenticated;

-- @down

drop function if exists comms.rbac_ensure_membership(uuid, uuid);
drop function if exists comms.can_access_project(uuid);

drop policy if exists role_grants_read on comms.role_grants;
drop policy if exists role_grants_write on comms.role_grants;
drop function if exists comms.rbac_allows(text, uuid, text, uuid);
drop table if exists comms.role_grants cascade;

-- public.roles, public.rbac_key_matches and public.rbac_touch_updated_at are
-- shared across the suite and are intentionally left in place — dropping them
-- would delete another product's role definitions.
